In [ ]:
How many rows will be fetched in the following query?
SELECT emp_id, name, salary FROM Emp WHERE salary < 1000 AND salary > 2000;
#No rows

Which of these queries shows only the 2nd highest product price?
#SELECT MAX(price) FROM Product WHERE price < (SELECT MAX(price) FROM Product);

Consider Emp table with following data:
Id Name Sex Salary
1 A m 2500
2 B f 1500
3 C m 5500
4 D f 500
Which of these queries shows 'm' in place of 'f' and 'f' in place of 'm' for 'sex' column?
#SELECT CASE sex WHEN 'm' THEN 'f' ELSE 'm' END AS sex FROM Emp; 

What will be the output of this query?
SELECT SUM(salary) / (SELECT SUM(salary) FROM Emp) AS result
FROM Emp GROUP BY dept_id;
#Ratio of sum of salaries of each dept. to total salaries of all employees 

How does a 1:N relationship among two entities get converted into tables during physical design?
#Key of entity from '1' side will be used as foreign key in 'N' side entity 

Which of these queries shows the customers who stay in the same locality (address & city) as 'Anita Rao'?
#SELECT custid, name FROM Customer c1 WHERE c1.name != 'Anita Rao' 
#AND EXISTS (SELECT 1 FROM Customer c2 WHERE c2.name = 'Anita Rao' AND c1.custid != c2.custid AND 
#c1.addressline2 = c2.addressline2 AND c1.city = c2.city);

Consider the following query that tries to get the customers who have placed some orders:
SELECT cust_id FROM Customer
WHERE EXISTS (SELECT cust_id FROM Ord_hdr WHERE status = 'Shipped');

If Customer table has 100 rows, Ord_hdr has 1000 rows, and only 50 customers have placed the orders (and shipped to them too), how many rows will this query fetch?
#100 

Which of these queries is equivalent to following query?
SELECT empid, COUNT(*) OVER(PARTITION BY deptid) FROM Emp;
#SELECT empid, (SELECT COUNT(*) FROM Emp e2 WHERE e1.deptid = e2.deptid) FROM Emp e1;

Assume there are 100 rows in Orders table. Output of query: SELECT COUNT(cust_id) FROM Orders WHERE cust_id = 125; is 15. Value of one cust_id is NULL.
What will be the output of SELECT COUNT(cust_id) FROM Orders WHERE cust_id <> 125;
# 85 

What will be the output of this query and why?
SELECT CASE WHEN NULL = NULL THEN ‘YES’ 
ELSE ‘NO’ END AS Result;
#NO 

Tables A & B both have one column (ID) each. Values of A are: 10, 20, 30, 40, 50. Values of B are: 10, 30, 50.
How to show values that only in A but not in B without using NOT keyword?
#SELECT A.id from A LEFT JOIN B ON A.id = B.id WHERE B.id IS NULL; 

Which of these following statements is/are TRUE?
i) There can be more than one primary key in a table
ii) There can be more than one foreign key in a table
iii) Primary key can be composite
iv) Foreign key can be composite
#Only ii), iii) and iv)

Emp table has 100 rows with no dept id assigned to 10 employees. Dept table has 30 rows with 10 departments having no employees. How many rows will be fetched if " Emp RIGHT JOIN Dept" is done based on common dept_id column between these two tables?
#100

The statement SELECT COUNT(*) FROM Orders; will give the total no. of rows in Orders table. What other COUNT(__) expressions will also give the same output?
#SELECT empid, (SELECT COUNT(*) FROM Emp e2 WHERE e1.deptid = e2.deptid) FROM Emp e1;

Which of these queries will result in an error?
#None of these will result in any error.